config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  resources :beverage_entries
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'beverage_entries#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_footer.html.erb
<nav class="max-w-[430px] mx-auto sm:flex md:hidden fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 bg-body-tertiary" style="font-family: 'Montserrat', sans-serif;">
  <div class="w-full mx-auto p-3 flex justify-around items-center">
    <!-- Home Link -->  
    <div class="text-center">
      <%= link_to root_path, class: "text-gray-600 hover:text-blue-500 #{'text-blue-500' if current_page?(root_path)}" do %>
        <div class="flex flex-col items-center">
          <i class="bi bi-house-fill text-xl"></i>
          <span class="text-xs mt-1">Home</span>
        </div>
      <% end %>
    </div>
    
    <!-- Copilot Link -->
    <div class="text-center">
      <%= link_to root_path, class: "text-gray-600 hover:text-blue-500 #{'text-blue-500' if current_page?(root_path)}" do %>
        <div class="flex flex-col items-center">
          <i class="bi bi-robot text-xl"></i>
          <span class="text-xs mt-1">Copilot</span>
        </div>
      <% end %>
    </div>
    
    <!-- Browse Link -->
    <div class="text-center">
      <%= link_to root_path, class: "text-gray-600 hover:text-blue-500 #{'text-blue-500' if current_page?(root_path)}" do %>
        <div class="flex flex-col items-center">
          <i class="bi bi-grid-3x3-gap-fill text-xl"></i>
          <span class="text-xs mt-1">Browse</span>
        </div>
      <% end %>
    </div>
    
    <!-- Profile Link -->
    <div class="text-center">
      <%= link_to edit_user_registration_path, class: "text-gray-600 hover:text-blue-500 #{'text-blue-500' if current_page?(edit_user_registration_path)}" do %>
        <div class="flex flex-col items-center">
          <i class="bi bi-person-fill text-xl"></i>
          <span class="text-xs mt-1">Profile</span>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<script src="https://cdn.tailwindcss.com"></script>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

app/views/shared/_header.html.erb
<div class="absolute top-[-320px] bottom-0 h-[559px] w-full bg-[linear-gradient(180deg,rgba(255,0,75,0)_39.18%,rgba(255,0,75,0.97)_86.76%)] rounded-b-[50px]">
  <div class="relative top-[340px] px-4 py-7.5 flex flex-col gap-7">
    <div class="border border-white rounded-[10px] py-[11px] text-center">
      <h6 class="text-[22px] text-white font-semibold">Hydration Tracker</h6>
    </div>
    <div class="flex items-center justify-between gap-3 text-white">
      <div class="size-[53px] rounded-full border border-white shadow-[0px_17px_23px_0px_#0A0A0A40,3px_4px_8px_0px_#FFFFFFB2]">
        <img src="<%= image_path('profile.svg') %>" alt="Profile" class="size-full" />
      </div>
      <div class="flex-1 text-left">
        <p class="text-xs">Good Afternoon </p>
        <h5 class="text-xl font-bold">Hey <%= @current_user&.first_name %>! 👋</h5>
      </div>
      <div class="size-[53px] rounded-full border border-white shadow-[0px_17px_23px_0px_#0A0A0A40,3px_4px_8px_0px_#FFFFFFB2] bg-white text-black">
        <%= link_to destroy_user_session_path, method: :delete, data: {turbo_confirm: 'Are you sure?'} do %>
          <img src="<%= image_path('logout.png') %>" alt="Profile" class="size-[53px]" />
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if current_user != true_user %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to stop_impersonating_madmin_impersonates_path, method: :post do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-body p-2 mb-3" data-bs-theme="dark">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link" do %>
              <span><i class="far fa-bell" aria-hidden="true"></i></span>
            <% end %>
          </li>

          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.admin? && respond_to?(:madmin_root_path) %>
                <div class="dropdown-divider"></div>
                <%= link_to "Admin Area", madmin_root_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="container mt-4 mx-auto">
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>