config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  resources :beverage_entries
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'beverage_entries#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/beverage_entry.rb
class BeverageEntry < ApplicationRecord
  belongs_to :user
  has_one :symptom, dependent: :destroy
  has_one_attached :photo
  
  validates :consumed_at, :category, :quantity, :quantity_unit, :temperature, presence: true
  
  accepts_nested_attributes_for :symptom, allow_destroy: true
  
  enum temperature: {
    very_cold: 0,
    chilled: 1,
    cool: 2,
    room_temperature: 3,
    warm: 4,
    hot: 5,
    very_hot: 6
  }

  after_create_commit { broadcast_prepend_to "beverage_entries" }
  after_destroy_commit { broadcast_remove_to "beverage_entries" }
  after_update_commit { broadcast_replace_to "beverage_entries" }



  CATEGORIES = {
    "Water-Based Beverages" => [
      "Plain Water", 
      "Infused Water (Lemon, Cucumber, Mint, Ginger)", 
      "Coconut Water", 
      "Electrolyte-Infused Water", 
      "Oral Rehydration Solutions"
    ],
    "Coffee-Based Beverages" => [
      "Black Coffee", 
      "Espresso", 
      "Americano", 
      "Cold Brew", 
      "Latte (Dairy-Based)", 
      "Latte (Plant-Based)", 
      "Cappuccino", 
      "Mocha"
    ],
    "Tea-Based Beverages" => [
      "Green Tea", 
      "Black Tea", 
      "White Tea", 
      "Oolong Tea", 
      "Herbal Tea (Peppermint, Chamomile, Ginger, Fennel, Licorice Root)", 
      "Matcha", 
      "Yerba Mate"
    ],
    "Juice & Smoothies" => [
      "Fresh Fruit Juice (Apple, Orange, Pomegranate, etc.)", 
      "Vegetable Juice (Carrot, Beet, Celery, etc.)", 
      "Blended Smoothies (Fruit-Based)", 
      "Blended Smoothies (Vegetable-Based)"
    ],
    "Dairy-Based Beverages" => [
      "Whole Milk", 
      "Low-Fat Milk", 
      "Skim Milk", 
      "Lactose-Free Milk", 
      "Kefir", 
      "Buttermilk"
    ],
    "Plant-Based Milks" => [
      "Almond Milk (Unsweetened)", 
      "Almond Milk (Sweetened)", 
      "Oat Milk (Unsweetened)", 
      "Oat Milk (Sweetened)", 
      "Soy Milk", 
      "Coconut Milk", 
      "Rice Milk", 
      "Hemp Milk"
    ],
    "Fermented & Probiotic Beverages" => [
      "Kombucha", 
      "Lassi", 
      "Yakult", 
      "Kvass"
    ],
    "Carbonated & Artificially Sweetened Drinks" => [
      "Regular Soda", 
      "Diet Soda", 
      "Sparkling Water", 
      "Energy Drinks", 
      "Sports Drinks (Gatorade, Powerade)"
    ],
    "Alcoholic Beverages" => [
      "Beer", 
      "Wine", 
      "Cider", 
      "Cocktails", 
      "Liquor (Vodka, Whiskey, Gin, Tequila)"
    ],
    "Other" => [
      "Other"
    ]
  }

  private

  def broadcast_remove(**rendering)
    broadcast_remove_to self, **rendering
  end
end

app/controllers/beverage_entries_controller.rb
class BeverageEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_beverage_entry, only: [:show, :edit, :update, :destroy]

  def index
    @beverage_entries = current_user.beverage_entries.order(consumed_at: :desc).limit(20)
  end

  def new
    @beverage_entry = current_user.beverage_entries.build
    @beverage_entry.build_symptom
  end

  def show
  end

  def edit
    @beverage_entry.build_symptom if @beverage_entry.symptom.nil?
  end

  def create
    @beverage_entry = current_user.beverage_entries.build(beverage_entry_params)
    if @beverage_entry.save
      respond_to do |format|
        format.turbo_stream { redirect_to beverage_entry_path(@beverage_entry), notice: 'Entry was created.' }
      end
    else
      respond_to do |format|
        format.turbo_stream { render :new, status: :unprocessable_entity, notice: @beverage_entry.errors }
      end
    end
  end

  def update
    if @beverage_entry.update(beverage_entry_params)
      respond_to do |format|
        format.turbo_stream { redirect_to @beverage_entry, notice: 'Beverage entry was successfully updated.' }
      end
      # redirect_to @beverage_entry, notice: 'Beverage entry was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @beverage_entry.destroy
    respond_to do |format|
      format.turbo_stream { redirect_to beverage_entries_url, notice: 'Beverage entry was successfully destroyed.' }
    end
  end

  private

  def set_beverage_entry
    @beverage_entry = current_user.beverage_entries.find(params[:id])
  end

  def beverage_entry_params
    params.require(:beverage_entry).permit(
      :consumed_at,
      :category,
      :subcategory,
      :quantity,
      :quantity_unit,
      :temperature,
      :notes,
      :photo,
      :symptoms_occurred,
      additions: [],
      symptoms_attributes: [
        :id, 
        :severity, 
        :onset_time, 
        :other_symptom, 
        :_destroy, 
        { name: [] }
      ]
    )
  end
end

app/views/beverage_entries/_beverage_entry.html.erb
<div id="<%= dom_id(beverage_entry) %>" class="container mt-3">
  <div class="card p-4 shadow">
    <div class="d-flex align-items-center">
      <% if beverage_entry.photo.attached? %>
        <%= image_tag beverage_entry.photo, class: "rounded me-2 border border-2 border-light", height: 100, width: 100, alt: "Beverage Photo" %>
      <% end %>

      <div>
        <h4 class="fw-bold mb-0"><%= beverage_entry.subcategory %></h4>
        <span class="text-muted">Recorded <%= time_ago_in_words(beverage_entry.created_at) %> ago</span>
      </div>
    </div>

    <hr>

    <!-- Beverage Details -->
    <div class="mt-3">
      <div class="row mb-2">
        <div class="col-md-6">
          <strong>Category:</strong> <%= beverage_entry.category %>
        </div>
        <div class="col-md-6">
          <strong>Consumed At:</strong> <%= beverage_entry.consumed_at.strftime("%B %d, %Y at %I:%M %p") %>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-md-6">
          <strong>Quantity:</strong> <%= "#{beverage_entry.quantity} #{beverage_entry.quantity_unit}" %>
        </div>
        <div class="col-md-6">
          <strong>Temperature:</strong>
          <% temperature_emojis = {
            'very_cold' => '❄️ Ice Cold (0°C / 32°F)',
            'chilled' => '🧊 Chilled (4°C / 40°F)',
            'cool' => '🥶 Cool (10°C / 50°F)',
            'room_temperature' => '🌡️ Room Temperature (20°C / 68°F)',
            'warm' => '🔥 Warm (50°C / 122°F)',
            'hot' => '☕ Hot (70°C / 158°F)',
            'very_hot' => '♨️ Boiling (100°C / 212°F)'
          } %>
          <span><%= temperature_emojis[beverage_entry.temperature] %></span>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-md-6">
          <strong>Additions:</strong>
          <% if beverage_entry.additions.present? %>
            <ul>
              <% beverage_entry.additions.each do |addition| %>
                <li><%= addition %></li>
              <% end %>
            </ul>
          <% else %>
            <span>None</span>
          <% end %>
        </div>
      </div>

      <% if beverage_entry.notes.present? %>
        <div class="mt-3">
          <strong>Notes:</strong>
          <p class="card bg-light p-2 mt-1"><%= beverage_entry.notes %></p>
        </div>
      <% end %>
    </div>

    <!-- Actions -->
    <div class="mt-4">    
      <%= link_to 'Edit', edit_beverage_entry_path(beverage_entry), class: "btn btn-outline-primary me-2" %>
      <%= button_to 'Delete', beverage_entry_path(beverage_entry), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger", form: { style: 'display: inline-block;' } %>
    </div>
  </div>
</div>

app/views/beverage_entries/_form.html.erb
<div class="max-w-[430px] mx-auto w-full" style="font-family: Montserrat, sans-serif">
  <div class="relative flex flex-col">
    <div class="absolute top-[-320px] bottom-0 h-[500px] w-full bg-[linear-gradient(180deg,rgba(255,0,75,0)_39.18%,rgba(255,0,75,0.97)_86.76%)] rounded-b-[50px]">
      <div class="relative top-[380px] px-4 py-7.5">
        <div class="flex items-center justify-center gap-4"> <!-Changed to flex row -->
          <div class="rounded-full border border-white size-[53px] flex items-center justify-center">
            <%= link_to root_path, class: "flex items-center justify-center bg-white rounded-full size-10 shadow-[0px_4px_10px_rgba(0,0,0,0.1)]" do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-[#FE2968]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
              </svg>
            <% end %>
          </div>
          <h6 class="text-[22px] text-white font-semibold"><%= title %></h6>
        </div>
      </div>
    </div>

    <div class="relative top-[150px] rounded-[40px] bg-white text-[#212121] shadow-[0px_5px_19px_0px_#6A6A6A29] w-full">
      <div class="mt-4 mb-12 px-[29px]">
        <%= form_with model: beverage_entry, local: true, data: { controller: "beverage-form" }, class: "space-y-6" do |f| %>
          <!-Date & Time field -->
          <div class="mb-6">
            <label class="block text-[#212121] text-sm font-medium mb-2">Date & Time of Consumption</label>
            <%= f.datetime_local_field :consumed_at, 
                class: "w-full border border-gray-300 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-[#FE2968] focus:border-transparent",
                required: true %>
          </div>
          
          <!-Beverage Category -->
          <div class="mb-6">
            <label class="block text-[#212121] text-sm font-medium mb-2">Beverage Category</label>
            <div class="relative w-full">
              <%= f.select :category, BeverageEntry::CATEGORIES.keys.map { |type| [type, type] }, 
                { include_blank: true, selected: @beverage_entry&.category || (params[:action] == 'new' ? BeverageEntry::CATEGORIES.keys.first : nil) },
                class: "appearance-none w-full border border-gray-300 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-[#FE2968] focus:border-transparent 
                        max-w-full overflow-hidden text-ellipsis 
                        [&_option]:bg-white [&_option]:text-black [&_option]:max-w-full [&_option]:overflow-hidden [&_option]:text-ellipsis",
                data: { action: "change->beverage-form#updateSubcategories" },
                required: true %>
              <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
                <svg class="w-5 h-5 text-[#FE2968]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                </svg>
              </div>
            </div>
          </div>
          
          <!-Subcategory -->
          <div class="mb-6">
            <label class="block text-[#212121] text-sm font-medium mb-2">Subcategory</label>
            <div class="relative w-full">
              <%= f.select :subcategory, [], 
                { include_blank: true }, 
                class: "appearance-none w-full border border-gray-300 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-[#FE2968] focus:border-transparent 
                        max-w-full overflow-hidden text-ellipsis 
                        [&_option]:bg-white [&_option]:text-black [&_option]:max-w-full [&_option]:overflow-hidden [&_option]:text-ellipsis",
                data: { beverage_form_target: "subcategory", selected_subcategory: f.object&.subcategory },
                required: true %>
              <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
                <svg class="w-5 h-5 text-[#FE2968]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                </svg>
              </div>
            </div>
          </div>
          <!-Quantity -->
          <div class="mb-6">
            <label class="block text-[#212121] text-sm font-medium mb-2">Quantity</label>
            <div class="flex gap-3">
                <div class="flex-1">
                  <%= f.number_field :quantity, 
                      class: "w-full border border-gray-300 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-[#FE2968] focus:border-transparent",
                      required: true, min: 0 %>
                </div>
                <div class="flex-1 relative">
                  <%= f.select :quantity_unit, [["ml", "ml"], ["oz", "oz"], ["cups", "cups"]], 
                      { selected: beverage_entry.quantity_unit },
                      class: "appearance-none w-full border border-gray-300 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-[#FE2968] focus:border-transparent",
                      required: true %>
                  <div class="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
                      <svg class="w-5 h-5 text-[#FE2968]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                      </svg>
                  </div>
                </div>
            </div>
          </div>
          <!-Temperature section -->
          <div class="mb-8">
            <h3 class="text-[#212121] text-xl font-bold text-center mb-4">Temperature</h3>
            <!-Temperature slider -->
            <div class="relative mb-4">
              <%= f.range_field :temperature, in: 0..6, 
                class: "w-full h-2 bg-gradient-to-r from-[#FF005B] to-[#FF005B] rounded-full appearance-none 
                  [&::-webkit-slider-thumb]:appearance-none 
                  [&::-webkit-slider-thumb]:w-4 
                  [&::-webkit-slider-thumb]:h-4 
                  [&::-webkit-slider-thumb]:bg-blue-500 
                  [&::-webkit-slider-thumb]:rounded-full 
                  [&::-webkit-slider-thumb]:cursor-pointer
                  [&::-moz-range-thumb]:appearance-none 
                  [&::-moz-range-thumb]:w-4 
                  [&::-moz-range-thumb]:h-4 
                  [&::-moz-range-thumb]:bg-blue-500 
                  [&::-moz-range-thumb]:rounded-full 
                  [&::-moz-range-thumb]:cursor-pointer",
                data: { action: "input->beverage-form#updateTemperatureLabel", beverage_form_target: "temperatureSlider" },
                value: BeverageEntry.temperatures[beverage_entry.temperature] %>
              <%= f.hidden_field :temperature, 
                data: { beverage_form_target: "temperatureValue" }, 
                value: beverage_entry.temperature %>
            </div>
            <!-Temperature indicator -->
            <div class="flex justify-center">
                <div class="inline-flex items-center gap-2 rounded-full px-4 py-2 text-[#FE2968]" data-beverage-form-target="temperatureLabel">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                      <path d="M14 14.76V3.5a2.5 2.5 0 0 0-5 0v11.26a4.5 4.5 0 1 0 5 0z"></path>
                  </svg>
                  <span class="text-sm font-medium">
                  <%= beverage_entry.temperature.present? ? BeverageEntry.temperatures.key(beverage_entry.temperature) : "Room Temperature (20°C / 68°F)" %>
                  </span>
                </div>
            </div>
          </div>
          <!-Additions section -->
          <div class="mb-8">
            <h3 class="text-[#212121] text-xl font-bold text-center mb-4">Additions</h3>
            <div class="grid grid-cols-2 gap-4">
                <% ["Sugar", "Milk", "Creamer", "Lemon", "Lime", "Honey", "Artificial Sweeteners", "Electrolyte Powder", "Protein Powder"].each do |additive| %>
                <div class="flex items-center gap-2">
                  <%= f.check_box :additions, 
                      { multiple: true, 
                        class: "hidden peer", 
                        id: "beverage_entry_additions_#{additive.parameterize}" }, 
                      additive, nil %>
                  <label for="beverage_entry_additions_<%= additive.parameterize %>" class="size-5 rounded border border-gray-300 peer-checked:border-[#FE2968] peer-checked:bg-[#FE2968] flex items-center justify-center cursor-pointer">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3 text-white hidden peer-checked:block" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                      </svg>
                  </label>
                  <label for="beverage_entry_additions_<%= additive.parameterize %>" class="text-sm cursor-pointer"><%= additive %></label>
                </div>
                <% end %>
            </div>
          </div>

          <!--Current Image -->

          <% if beverage_entry.photo.attached? %>
            <div class="mb-8">
              <label class="block text-[#212121] text-sm font-medium mb-2">Available Image</label>
              <div class="relative max-w-xs mx-auto mb-4">
                <%= image_tag beverage_entry.photo, class: "rounded-lg border border-gray-200 max-h-48 w-auto" %>
              </div>
            </div>
          <% end %>

          <!-Upload photo section -->
          <div class="mb-8">
            <label class="block text-[#212121] text-sm font-medium mb-2">Upload a photo (optional)</label>
            
            <div class="flex flex-col gap-4">
              <!-File input button and name display -->
              <div class="flex gap-2">
                <label for="beverage_entry_photo" class="bg-[#FE2968] text-white text-sm font-medium px-4 py-2 rounded-lg cursor-pointer hover:bg-[#E51E5A] transition-colors">
                  Choose file
                </label>
                <div class="flex-1 bg-[#FFD6E4] text-[#212121] text-sm px-4 py-2 rounded-lg overflow-hidden truncate">
                  <%= f.file_field :photo, 
                      class: "hidden", 
                      id: "beverage_entry_photo",
                      data: { action: "change->beverage-form#handleFileUpload" } %>
                  <span id="file-name" data-beverage-form-target="fileName">No file chosen</span>
                </div>
              </div>
              
              <!-Image preview container (hidden by default) -->
              <div data-beverage-form-target="previewContainer" class="hidden">
                <div class="relative max-w-xs mx-auto">
                  <img id="image-preview" class="rounded-lg border border-gray-200 max-h-48 w-auto" src="" alt="Preview">
                  <button type="button" 
                          data-action="click->beverage-form#removeImage"
                          class="absolute top-2 right-2 bg-red-500 text-white rounded-full p-1 hover:bg-red-600 transition-colors">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                      <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </div>

          <!-Submit button -->
          <%= f.submit submit_text, 
          class: "w-full bg-[#FE2968] text-white text-lg font-semibold py-4 rounded-full shadow-[0px_4px_10px_rgba(254,41,104,0.3)] hover:bg-[#FE2968]/90 focus:outline-none focus:ring-2 focus:ring-[#FE2968] focus:ring-offset-2" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/beverage_entries/_symptom_fields.html.erb
<!-- filepath: /home/developer/google_oauth_jumpstart/app/views/beverage_entries/_symptom_fields.html.erb -->
<div class="mb-2 border p-3">
  <%= form.label :name, "Name" %>
  <%= form.select :name, options_for_select(Symptom::ALLOWED_NAMES.map { |name| [name, name] }, selected: form.object.name), {}, class: "form-select mt-2", multiple: true %>
  <%= form.label :severity, "Severity" %>
  <%= form.select :severity, Symptom.severities.keys.map { |k| [k.humanize, k] }, {}, class: "form-select mt-2" %>
  <%= form.label :onset_time, "Onset Time" %>
  <%= form.select :onset_time, Symptom.onset_times.keys.map { |k| [k.humanize, k] }, {}, class: "form-select mt-2" %>
  <%= link_to "Remove", "#", class: "btn btn-danger mt-2", data: { action: "nested-form#remove" } %>
  <%= form.hidden_field :_destroy %>
</div>

app/views/beverage_entries/create.turbo_stream.erb
<%= turbo_stream.prepend "beverage_entries", partial: "beverage_entries/beverage_entry", locals: { beverage_entry: @beverage_entry } %>

app/views/beverage_entries/edit.html.erb
<%= render 'form',
    title: 'Edit Hydration Entry',
    beverage_entry: @beverage_entry,
    action_url: beverage_entry_path(@beverage_entry),
    method: :patch,
    submit_text: 'Update Beverage Entry' %>

app/views/beverage_entries/index.html.erb
<div class="max-w-[430px] mx-auto w-full" style="font-family: Montserrat, sans-serif">
  <div class="relative flex flex-col">
  
    <%= render 'shared/header'%>
    
    <div class="relative top-[210px] rounded-[40px] bg-white text-[#212121] shadow-[0px_5px_19px_0px_#6A6A6A29] w-full min-h-[300px] max-h-[70vh] overflow-y-auto no-scrollbar py-[20px] px-[10px]">
      <div class="py-[40px] px-[29px]">
        <h5 class="text-[#212121] mb-2 text-xl font-bold">Ready to track your beverages details today?</h5>
        
        <%= link_to new_beverage_entry_path, class: "no-underline" do %>
          <div class="flex items-center gap-3 p-2 rounded-[25px] py-[11px] justify-center text-center shadow-[4px_13px_51.9px_0px_#29292933] bg-[linear-gradient(0deg,#FE2968,#FE2968),radial-gradient(63.11%_63.11%_at+31.97%_19.67%,rgba(255,_255,_255,_0.7)_0%,rgba(255,_255,_255,_0)_69.79%,rgba(255,_255,_255,_0)_100%)]">
            <span class="block border-2 border-white text-white text-xl font-bold rounded-full size-7 flex items-center justify-center">
              +
            </span>
            <h6 class="text-base text-white font-semibold">Record Beverage Data</h6>
          </div>
        <%end%>

      </div>

      <div class="mt-4 mb-6 px-[29px]">
        <div class="rounded-[30px] bg-white shadow-[0px_5px_19px_0px_#6A6A6A29] p-6">
          <div class="text-center">
            <p class="text-[#212121] text-base font-medium mb-2">Day</p>
            <h2 class="text-[#FE2968] text-5xl font-bold mb-2">01</h2>
            <p class="text-[#212121] text-sm mb-6">Great start! You've built a 1-day streak.</p>

            <div class="flex justify-center gap-4 mb-6">
              <div class="text-[#FE2968] text-sm font-medium">M</div>
              <div class="text-[#FE2968] text-sm font-medium">T</div>
              <div class="text-[#FE2968] text-sm font-medium">W</div>
              <div class="text-[#FE2968] text-sm font-medium">T</div>
              <div class="flex items-center justify-center size-6 rounded-full bg-[#FE2968] text-white text-sm font-medium">
                F
              </div>
              <div class="text-[#FE2968] text-sm font-medium">S</div>
              <div class="text-[#FE2968] text-sm font-medium">S</div>
            </div>

            <button class="w-full border border-[#FE2968] text-[#FE2968] rounded-full py-3 font-semibold">
              Show All Data
            </button>

            </div>
            </div>
            
      </div>

      <div id="beverage_entries" class="mt-6 space-y-4">
        <% if @beverage_entries.any? %>
          <%= render @beverage_entries %>
        <% end %>
      </div>

    </div>
   
  </div>

</div>

app/views/beverage_entries/new.html.erb
<%= render 'form',
title: 'New Hydration',
beverage_entry: @beverage_entry || BeverageEntry.new,
action_url: beverage_entries_path,
method: :post,
submit_text: 'Create Beverage Entry' %>

app/views/beverage_entries/new.turbo_stream.erb
<%= turbo_stream.replace "new_beverage_form", partial: "beverage_entries/form", locals: { beverage_entry: @beverage_entry, title: 'Hydration Tracker Form', action_url: beverage_entries_path,method: :post,submit_text: 'Create Beverage Entry'  } %>

app/views/beverage_entries/show.html.erb
<div class="max-w-[430px] mx-auto w-full" style="font-family: Montserrat, sans-serif">
  <div class="relative flex flex-col">
    <%= render 'shared/header'%>
    
    <div class="relative top-[210px] rounded-[40px] bg-white text-[#212121] shadow-[0px_5px_19px_0px_#6A6A6A29] w-full">
      <div class="py-[40px] px-[29px]">
        <h5 class="text-[#212121] mb-2 text-xl font-bold">Ready to track your beverages details today?</h5>
        
        <%= link_to new_beverage_entry_path, class: "no-underline" do %>
          <div class="flex items-center gap-3 p-2 rounded-[25px] py-[11px] justify-center text-center shadow-[4px_13px_51.9px_0px_#29292933] bg-[linear-gradient(0deg,#FE2968,#FE2968),radial-gradient(63.11%_63.11%_at+31.97%_19.67%,rgba(255,_255,_255,_0.7)_0%,rgba(255,_255,_255,_0)_69.79%,rgba(255,_255,_255,_0)_100%)]">
            <span class="block border-2 border-white text-white text-xl font-bold rounded-full size-7 flex items-center justify-center">
              +
            </span>
            <h6 class="text-base text-white font-semibold">Record Beverage Data</h6>
          </div>
        <%end%>

      </div>

      <div id="beverage_entries">
        <%= render partial: 'beverage_entry', locals: { beverage_entry: @beverage_entry } %>
      </div>

      <div class="rounded-[30px] bg-white shadow-[0px_5px_19px_0px_#6A6A6A29] p-6">           

        <%= button_to "Show All Data", 
          beverage_entries_path, 
          method: :get, 
          class: "w-full border border-[#FE2968] text-[#FE2968] rounded-full py-3 font-semibold",
          data: { turbo_frame: "beverage_entries" } %>
      </div>

      </div>
    </div>
  </div>
</div>